version: "3.9"

services:
  db:
    image: postgres:10
    container_name: fastapi_db
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
  web:
    container_name: fastapi_web
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: fast-api
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - db