version: "3.9"

services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    entrypoint: docker/entrypoint.sh
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - db